### ISSUE TITLE
GPS sensor

### ISSUE THREAD

**Issue by RandDruid** [UmerCodez/SensaGram#1]
In the client example I can see the "android.gps" sensor. But this sensor is not in the app and can't enable its output.
What could be the problem?
My phone is Android 14 / Color OS 14.0

**Comment by UmerCodez** [comment]
Which version of the app are you currently using? The GPS feature was introduced in version 1.3.0, which has not yet been published on F-Droid. It typically takes 4 to 5 days for F-Droid to release the latest updates.

If you are using the [latest version](https://github.com/umer0586/SensaGram/releases) from the releases section, you can find the GPS option at the bottom of the sensor list by scrolling all the way down.

**Comment by RandDruid** [comment]
Yes, you are right, I am using version 1.2.0 from F-Droid. I will check it on newer version when possible.
